version: '3.1'

services:

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: 1057405bcltd
      MONGO_INITDB_ROOT_PASSWORD: bittrex

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: 1057405bcltd
      ME_CONFIG_MONGODB_ADMINPASSWORD: bittrex
      ME_CONFIG_MONGODB_URL: mongodb://1057405bcltd:bittrex@mongo:27017/